[package]
name = "lexer_type"
version = "0.1.0"
authors = ["Tim Martin <timothy.martin@kcl.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lrlex = "0.9.1"

[patch.crates-io]
lrlex = { path = "../lrlex" }
